import type { Property } from '@imovdigital/types';

const baseImage = (seed: string) => ({
  url: `https://picsum.photos/seed/${seed}/1200/800`,
  order: 0,
  alt: '',
});

function mock(overrides: Partial<Property>): Property {
  const id = overrides.id || 'mock';
  return {
    id,
    tenantId: 'demo',
    title: 'Imóvel de demonstração',
    description: 'Este é um exemplo de descrição de imóvel. Cadastre seus imóveis para ver os dados reais aqui.',
    slug: id,
    type: 'APARTMENT' as any,
    listingType: 'SALE' as any,
    price: 850000,
    rentPrice: null,
    condoFee: null,
    iptuYearly: null,
    area: 120,
    usableArea: null,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 2,
    floor: null,
    totalFloors: null,
    yearBuilt: null,
    neighborhood: 'Centro',
    city: 'Florianópolis',
    state: 'SC',
    zipCode: '88010-000',
    fullAddress: 'Rua Demonstração, 100 - Centro, Florianópolis - SC',
    latitude: -27.5954,
    longitude: -48.5480,
    amenities: ['Piscina', 'Academia', 'Vaga coberta', 'Portaria 24h'],
    petFriendly: true,
    furnished: false,
    financingAvailable: true,
    images: [baseImage(`${id}-1`), baseImage(`${id}-2`), baseImage(`${id}-3`), baseImage(`${id}-4`), baseImage(`${id}-5`)],
    videoUrl: null,
    active: true,
    featured: true,
    metaTitle: null,
    metaDescription: null,
    createdAt: new Date('2026-01-15') as any,
    updatedAt: new Date('2026-01-15') as any,
    ...overrides,
  };
}

export const MOCK_PROPERTIES: Property[] = [
  mock({
    id: 'mock-1',
    title: 'Apartamento com vista para o mar',
    type: 'APARTMENT' as any,
    listingType: 'SALE' as any,
    price: 1250000,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 2,
    area: 145,
    neighborhood: 'Jurerê Internacional',
    city: 'Florianópolis',
    state: 'SC',
    fullAddress: 'Rua das Acácias, 123 - Jurerê Internacional, Florianópolis - SC',
    description: 'Lindo apartamento com vista panorâmica do mar, totalmente reformado e mobiliado. Localização privilegiada, próximo a restaurantes, padarias e à praia.\n\nA cobertura conta com piscina aquecida, churrasqueira e área gourmet completa.',
    amenities: ['Piscina aquecida', 'Academia', '2 vagas cobertas', 'Portaria 24h', 'Salão de festas', 'Churrasqueira'],
    featured: true,
  }),
  mock({
    id: 'mock-2',
    title: 'Casa contemporânea no Lago Sul',
    type: 'HOUSE' as any,
    listingType: 'SALE' as any,
    price: 2800000,
    bedrooms: 4,
    suites: 2,
    bathrooms: 4,
    parkingSpots: 4,
    area: 380,
    neighborhood: 'Lago Sul',
    city: 'Brasília',
    state: 'DF',
    fullAddress: 'SHIS QL 10 - Lago Sul, Brasília - DF',
    description: 'Casa contemporânea de alto padrão em condomínio fechado.',
    amenities: ['Piscina', 'Sauna', 'Home theater', 'Garagem para 4 carros', 'Jardim'],
    featured: true,
  }),
  mock({
    id: 'mock-3',
    title: 'Studio compacto no Itaim',
    type: 'APARTMENT' as any,
    listingType: 'RENT' as any,
    price: 0,
    rentPrice: 4200,
    condoFee: 850,
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parkingSpots: 1,
    area: 38,
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    state: 'SP',
    fullAddress: 'Rua Joaquim Floriano, 500 - Itaim Bibi, São Paulo - SP',
    description: 'Studio mobiliado em prédio novo, próximo ao metrô.',
    amenities: ['Academia', 'Coworking', 'Mobiliado', 'Internet inclusa'],
    featured: false,
  }),
  mock({
    id: 'mock-4',
    title: 'Cobertura duplex em Ipanema',
    type: 'APARTMENT' as any,
    listingType: 'SALE' as any,
    price: 5600000,
    bedrooms: 4,
    suites: 3,
    bathrooms: 5,
    parkingSpots: 3,
    area: 280,
    neighborhood: 'Ipanema',
    city: 'Rio de Janeiro',
    state: 'RJ',
    fullAddress: 'Rua Vinícius de Moraes, 200 - Ipanema, Rio de Janeiro - RJ',
    description: 'Cobertura duplex com piscina privativa e vista para o mar.',
    amenities: ['Piscina privativa', 'Vista mar', 'Terraço', '3 vagas', 'Vista panorâmica'],
    featured: true,
  }),
  mock({
    id: 'mock-5',
    title: 'Casa com piscina em condomínio',
    type: 'HOUSE' as any,
    listingType: 'BOTH' as any,
    price: 1850000,
    rentPrice: 9500,
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parkingSpots: 3,
    area: 220,
    neighborhood: 'Cyrela Landscape',
    city: 'Cotia',
    state: 'SP',
    fullAddress: 'Cyrela Landscape - Cotia, SP',
    description: 'Casa em condomínio fechado com infraestrutura completa.',
    amenities: ['Condomínio fechado', 'Piscina', 'Quadra', 'Playground', 'Segurança 24h'],
    featured: false,
  }),
  mock({
    id: 'mock-6',
    title: 'Loft industrial reformado',
    type: 'APARTMENT' as any,
    listingType: 'RENT' as any,
    price: 0,
    rentPrice: 6800,
    condoFee: 1200,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    area: 95,
    neighborhood: 'Vila Madalena',
    city: 'São Paulo',
    state: 'SP',
    fullAddress: 'Rua Aspicuelta, 600 - Vila Madalena, São Paulo - SP',
    description: 'Loft com pé-direito alto, totalmente reformado.',
    amenities: ['Pé-direito alto', 'Reformado', 'Mobiliado', 'Pet-friendly'],
    featured: false,
  }),
];
